---
- name: Check if skip_zsh is set
  ansible.builtin.debug:
    var: skip_zsh

- name: Install zsh if skip_zsh is not true
  when: skip_zsh is false
  block:
    - name: Install zsh and plugins
      ansible.builtin.include_tasks:
        file: zsh.yaml
    - name: Install zsh plugins
      ansible.builtin.include_tasks:
        file: zsh_plugins.yaml
