---
- name: Display tool_zsh_skip
  ansible.builtin.debug:
    var: tool_zsh_skip

- name: Install zsh if tool_zsh_skip is not true
  when: tool_zsh_skip is false
  block:
    - name: Install zsh and plugins
      ansible.builtin.include_tasks:
        file: zsh.yaml
    - name: Install zsh plugins
      ansible.builtin.include_tasks:
        file: zsh_plugins.yaml
