---
- name: Setup user's sudo permission
  when: ansible_user != "root"
  ansible.builtin.include_tasks:
    file: sudo.yaml
    apply:
      become: true
      become_user: root

- name: Setup user (ansible_user)
  ansible.builtin.include_tasks:
    file: user.yaml
