---
- name: Install useful packages
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - htop # top
      - ncdu # du
      - duf # df
      - ripgrep # grep
      - fd-find # find
      - bat # cat
      - fzf # find
      - jq # json format

- name: Check Debian 12+
  ansible.builtin.set_fact:
    packages_os_is_debian_12: true
  when:
    - ansible_facts['distribution'] == 'Debian'
    - ansible_facts['distribution_major_version'] | int >= 12

- name: Check Ubuntu 24.04+
  ansible.builtin.set_fact:
    packages_os_is_ubuntu_24: true
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_major_version'] | int >= 24

- name: Install useful packages (Debian >= 12, Ubuntu >= 24)
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - tre-command # tree
  when: packages_os_is_debian_12 or packages_os_is_ubuntu_24

- name: Install ls alternative exa (Ubuntu < 24)
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - exa # ls
  when: not packages_os_is_ubuntu_24

- name: Install ls alternative exa (Ubuntu >= 24)
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - eza # ls
  when: packages_os_is_ubuntu_24

- name: Delete Block - Set alias exa
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - exa"
    state: absent
    create: true
  loop:
    - $HOME/.bash_aliases
    - $HOME/.oh-my-zsh/custom/alias_exa.zsh

- name: Set alias for ls alternative - exa
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ls"
    block: |
      alias ll='exa -l'
      alias la='exa -la'
    create: true
    mode: '644'
    state: present
  loop:
    - $HOME/.bash_aliases
    - $HOME/.oh-my-zsh/custom/alias_exa.zsh
  when: not packages_os_is_ubuntu_24

- name: Set alias for ls alternative - eza
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ls"
    block: |
      alias ll='eza -l'
      alias la='eza -la'
    create: true
    mode: '644'
    state: present
  loop:
    - $HOME/.bash_aliases
    - $HOME/.oh-my-zsh/custom/alias_exa.zsh
  when: packages_os_is_ubuntu_24

- name: Set alias for fd-find
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - fd-find"
    block: |
      alias fd='fdfind'
    create: true
    mode: '644'
    state: present
  loop:
    - $HOME/.bash_aliases
    - $HOME/.oh-my-zsh/custom/alias_fd-find.zsh

- name: Set alias for bat
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bat"
    block: |
      alias bat='batcat'
    create: true
    mode: '644'
    state: present
  loop:
    - $HOME/.bash_aliases
    - $HOME/.oh-my-zsh/custom/alias_bat.zsh

- name: Setup config dir for bat
  ansible.builtin.file:
    path: $HOME/.config/bat/
    state: directory
    mode: '755'

- name: Config theme for bat
  ansible.builtin.copy:
    dest: $HOME/.config/bat/config
    content: |
      # Set the theme to "Dracula"
      --theme="Dracula"
    mode: '644'

- name: Insert an empty line before the marker line
  ansible.builtin.replace:
    path: $HOME/.bash_aliases
    regexp: '(?<=.\n)^(# BEGIN ANSIBLE MANAGED BLOCK.*)$'
    replace: '\n\1'

- name: Insert an empty line after the marker line
  ansible.builtin.replace:
    path: $HOME/.bash_aliases
    regexp: '^(# END ANSIBLE MANAGED BLOCK.*)$(?=\n.)'
    replace: '\1\n'
