---
- name: Install prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yaml
    apply:
      become: true
      become_user: root

- name: Install python packages
  ansible.builtin.include_tasks:
    file: python.yaml
    apply:
      become: true
      become_user: root

- name: Install apt packages
  ansible.builtin.include_tasks:
    file: apt.yaml
