---
- name: Install python prerequisites
  ansible.builtin.include_tasks:
    file: python_prerequisites.yaml
    apply:
      become: true
      become_user: root

- name: Install python packages via Pipx
  block:
    - name: Install for root
      ansible.builtin.include_tasks:
        file: python_pipx.yaml
        apply:
          become: true
          become_user: root
    - name: Install for ansible user
      ansible.builtin.include_tasks:
        file: python_pipx.yaml

- name: Install apt packages
  ansible.builtin.include_tasks:
    file: apt.yaml

- name: Install manual packages
  ansible.builtin.include_tasks:
    file: manual.yaml
