---
- name: install prerequisites
  include_tasks:
    file: prerequisites.yaml
    apply:
      become: true
      become_user: root

- name: install python packages
  include_tasks:
    file: python.yaml
    apply:
      become: true
      become_user: root

- name: install apt packages
  include_tasks:
    file: apt.yaml
