---
- name: Copy skeleton for root user
  ansible.builtin.copy:
    src: "/etc/skel/{{ item }}"
    dest: "/root/{{ item }}"
    mode: '600'
  loop:
    - .profile
    - .bashrc
    - .bash_logout
  register: result

- name: Setup git
  ansible.builtin.include_role:
    name: tool_git

- name: Setup vim
  ansible.builtin.include_role:
    name: tool_vim
