---
- name: Install necessary packages
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker's official GPG Key
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution }}/gpg"
    dest: /etc/apt/trusted.gpg.d/.asc
