---
- name: Upgrade restic/rclone
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Upgrade rclone (selfupdate)
      ansible.builtin.command:
        cmd: rclone selfupdate
      register: rclone
      changed_when: '"rclone is up to date" not in rclone.stderr'
      failed_when: rclone.rc != 0

    - name: Show Output
      ansible.builtin.debug:
        msg: "{{ rclone.stdout_lines + rclone.stderr_lines }}"

    - name: Upgrade restic (self update)
      ansible.builtin.command: restic self-update
      register: restic
      changed_when: '"restic is up to date" not in restic.stdout'
      failed_when: rclone.rc != 0

    - name: Show Output
      ansible.builtin.debug:
        msg: "{{ restic.stdout_lines }}"
