---
- name: System Update
  hosts: all
  become: true
  become_user: root
  vars:
    local: local
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: List installed and updated packages
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log || echo "N/A" | cut -d " " -f 3-5
        executable: /usr/bin/bash
      register: packages
      changed_when: packages.stdout_lines is undefined

    - name: Show Output
      ansible.builtin.debug:
        msg: "{{ packages.stdout_lines }}"

    - name: Check if a reboot is needed on all servers
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Print if reboot is skipped
      ansible.builtin.debug:
        msg: "skip_reboot: {{ skip_reboot }}"

    - name: Reboot the box if kernel updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      throttle: 1
      when:
        - not skip_reboot
        - reboot_required_file.stat.exists
        - local not in group_names

    - name: Cleanup apt packages (autoremove)
      ansible.builtin.apt:
        autoremove: true
        purge: true
        clean: true
